### ISSUE TITLE
New API for easier plotting

### ISSUE THREAD

**Issue by htian97** [smu-tao-group/xymol#4]
Currently, the users will need to featurize each of the SMILES through [drop_each_atom](https://github.com/smu-tao-group/xymol/blob/main/xymol/xymol.py#L55), use their own models for prediction and return weights back to [plot_similarity_map](https://github.com/smu-tao-group/xymol/blob/main/xymol/xymol.py#L123). 

It's better that we can do this on our side. We can have a new API to take user-input featurizer and model and do the above things.

**Comment by gitconnoisseur** [comment]
Closed after adding create_map to xymol.py

**Comment by htian97** [comment]
I downgraded your write permission. You will need to fork repo, do your commits and create a PR. All codes will need to be reviewed and approved. 

Any new code will need to have the same style and pass style checking (pylint); comes with solid test cases; pass CD/CI checks. You need to revise your codes accordingly.
